-- Azim Abzar: public cart / order request engine
-- Active production function definition captured from Supabase.
create table if not exists private.azim_cart_rate_limits (
  id bigint generated by default as identity primary key,
  ip inet,
  mobile text,
  created_at timestamptz not null default now()
);
create index if not exists azim_cart_rate_limits_ip_idx on private.azim_cart_rate_limits(ip, created_at desc);
create index if not exists azim_cart_rate_limits_mobile_idx on private.azim_cart_rate_limits(mobile, created_at desc);

CREATE OR REPLACE FUNCTION public.azim_cart_checkout(p_mode text DEFAULT 'preview'::text, p_full_name text DEFAULT NULL::text, p_mobile text DEFAULT NULL::text, p_email text DEFAULT NULL::text, p_address text DEFAULT NULL::text, p_city text DEFAULT NULL::text, p_discount_code text DEFAULT NULL::text, p_items jsonb DEFAULT '[]'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_mode text := lower(trim(coalesce(p_mode,'preview')));
  v_mobile text := regexp_replace(trim(coalesce(p_mobile,'')), '\s+', '', 'g');
  v_code text := upper(regexp_replace(trim(coalesce(p_discount_code,'')), '\s+', '', 'g'));
  v_customer_id uuid := null;
  v_discount record;
  v_discount_id uuid := null;
  v_discount_code text := null;
  v_discount_amount bigint := 0;
  v_subtotal bigint := 0;
  v_eligible bigint := 0;
  v_total bigint := 0;
  v_shipping bigint := 0;
  v_usage bigint := 0;
  v_customer_usage bigint := 0;
  v_has_order boolean := false;
  v_order_id uuid := null;
  v_order_code text := null;
  v_ip inet := null;
  v_ip_text text := null;
  v_lines jsonb := '[]'::jsonb;
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id uuid;
  v_variant text;
  v_variant_price bigint;
  v_unit_price bigint;
  v_quantity bigint;
  v_line_total bigint;
  v_count integer := 0;
  v_result jsonb;
begin
  if v_mode not in ('preview','submit') then
    raise exception 'حالت درخواست نامعتبر است.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'سبد خرید نامعتبر است.';
  end if;

  select count(*) into v_count from jsonb_array_elements(p_items);
  if v_count < 1 then
    raise exception 'سبد خرید خالی است.';
  end if;
  if v_count > 30 then
    raise exception 'حداکثر ۳۰ قلم در هر درخواست سفارش مجاز است.';
  end if;

  if v_mode = 'submit' then
    if length(trim(coalesce(p_full_name,''))) < 2 then
      raise exception 'نام و نام خانوادگی را وارد کنید.';
    end if;
    if length(v_mobile) < 7 or length(v_mobile) > 20 then
      raise exception 'شماره موبایل واردشده معتبر نیست.';
    end if;
  end if;

  if v_mobile <> '' then
    select c.id into v_customer_id
    from public.customers c
    where c.mobile = v_mobile
    limit 1;
  end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    begin
      v_product_id := (v_item->>'product_id')::uuid;
    exception when others then
      raise exception 'شناسه یکی از محصولات نامعتبر است.';
    end;

    v_variant := nullif(trim(coalesce(v_item->>'variant_label','')), '');
    v_quantity := coalesce((v_item->>'quantity')::bigint, 1);

    if v_quantity < 1 or v_quantity > 99 then
      raise exception 'تعداد هر محصول باید بین ۱ تا ۹۹ باشد.';
    end if;

    select * into v_product
    from public.products
    where id = v_product_id
    limit 1;

    if not found then
      raise exception 'یکی از محصولات دیگر در کاتالوگ وجود ندارد.';
    end if;

    if v_product.is_active = false then
      raise exception 'محصول «%» در حال حاضر قابل سفارش نیست.', v_product.name;
    end if;

    v_unit_price := v_product.price;
    v_variant_price := null;

    if v_variant is not null then
      select nullif(trim(coalesce(v->>'price','')), '')::bigint
        into v_variant_price
      from jsonb_array_elements(coalesce(v_product.variants,'[]'::jsonb)) v
      where coalesce(v->>'size', v->>'label', v->>'name') = v_variant
      limit 1;

      if not found then
        raise exception 'سایز / مدل انتخاب‌شده برای «%» دیگر وجود ندارد.', v_product.name;
      end if;

      if v_variant_price is not null then
        v_unit_price := v_variant_price;
      end if;
    end if;

    if v_unit_price is null or v_unit_price <= 0 then
      raise exception 'قیمت محصول «%» ثبت نشده و قابل سفارش آنلاین نیست.', v_product.name;
    end if;

    if coalesce(v_product.discount_is_active,false)
       and (v_product.discount_starts_at is null or now() >= v_product.discount_starts_at)
       and (v_product.discount_ends_at is null or now() <= v_product.discount_ends_at)
       and v_product.discount_value is not null
       and v_product.discount_value > 0 then
      if v_product.discount_type = 'percentage' then
        v_unit_price := floor(v_unit_price * (100 - least(100,greatest(1,v_product.discount_value))) / 100.0)::bigint;
      elsif v_product.discount_type = 'fixed' then
        v_unit_price := greatest(0, v_unit_price - v_product.discount_value);
      end if;
    end if;

    v_line_total := v_unit_price * v_quantity;
    v_subtotal := v_subtotal + v_line_total;
    v_lines := v_lines || jsonb_build_array(jsonb_build_object(
      'product_id', v_product.id,
      'product_name', v_product.name,
      'sku', v_product.code,
      'variant_label', v_variant,
      'quantity', v_quantity,
      'unit_price', v_unit_price,
      'line_total', v_line_total,
      'brand', v_product.brand,
      'category_name', coalesce(v_product.category_name,v_product.cat)
    ));
  end loop;

  if v_code <> '' then
    if v_mode = 'submit' then
      select * into v_discount
      from public.discounts
      where upper(code) = v_code
      limit 1
      for update;
    else
      select * into v_discount
      from public.discounts
      where upper(code) = v_code
      limit 1;
    end if;

    if not found then
      raise exception 'کد تخفیف پیدا نشد.';
    end if;
  else
    select * into v_discount
    from public.discounts
    where auto_apply = true
    order by priority desc, created_at desc
    limit 1;
  end if;

  if v_discount.id is not null then
    v_discount_id := v_discount.id;
    v_discount_code := v_discount.code;

    if not v_discount.is_active then
      raise exception 'این کد تخفیف غیرفعال است.';
    end if;

    if now() < v_discount.starts_at then
      raise exception 'زمان شروع این کد تخفیف نرسیده است.';
    end if;

    if v_discount.ends_at is not null and now() > v_discount.ends_at then
      raise exception 'این کد تخفیف منقضی شده است.';
    end if;

    if v_subtotal < coalesce(v_discount.min_order_amount,0) then
      raise exception 'حداقل مبلغ سبد برای این کد رعایت نشده است.';
    end if;

    select count(*) into v_usage
    from public.discount_redemptions r
    left join public.orders o on o.id=r.order_id
    where r.discount_id = v_discount.id
      and coalesce(o.status,'') <> 'cancelled';

    if v_discount.usage_limit is not null and v_usage >= v_discount.usage_limit then
      raise exception 'ظرفیت استفاده از این کد تکمیل شده است.';
    end if;

    if v_customer_id is not null then
      select count(*) into v_customer_usage
      from public.discount_redemptions r
      left join public.orders o on o.id=r.order_id
      where r.discount_id = v_discount.id
        and r.customer_id = v_customer_id
        and coalesce(o.status,'') <> 'cancelled';

      if v_customer_usage >= coalesce(v_discount.per_customer_limit,1) then
        raise exception 'این مشتری قبلاً از سقف مجاز این کد استفاده کرده است.';
      end if;

      select exists(
        select 1 from public.orders o
        where o.customer_id = v_customer_id and o.status <> 'cancelled'
      ) into v_has_order;
    else
      v_has_order := false;
    end if;

    if v_discount.first_order_only and v_has_order then
      raise exception 'این کد فقط برای اولین خرید قابل استفاده است.';
    end if;

    if v_discount.applies_to = 'customers' then
      if v_customer_id is null then
        raise exception 'این کد برای مشتری مشخصی صادر شده و نیاز به شماره موبایل همان مشتری دارد.';
      end if;
      if not exists(
        select 1 from public.discount_customers dc
        where dc.discount_id=v_discount.id and dc.customer_id=v_customer_id
      ) then
        raise exception 'این کد برای این مشتری صادر نشده است.';
      end if;
    end if;

    for v_item in select value from jsonb_array_elements(v_lines) loop
      if v_discount.applies_to = 'all' then
        v_eligible := v_eligible + coalesce((v_item->>'line_total')::bigint,0);
      elsif v_discount.applies_to = 'products' and exists(
        select 1 from public.discount_products dp
        where dp.discount_id=v_discount.id
          and dp.product_id=(v_item->>'product_id')::uuid
      ) then
        v_eligible := v_eligible + coalesce((v_item->>'line_total')::bigint,0);
      elsif v_discount.applies_to = 'categories' and exists(
        select 1
        from public.discount_categories dc
        join public.categories c on c.id=dc.category_id
        where dc.discount_id=v_discount.id
          and c.name=coalesce(v_item->>'category_name','')
      ) then
        v_eligible := v_eligible + coalesce((v_item->>'line_total')::bigint,0);
      elsif v_discount.applies_to = 'brands' and exists(
        select 1
        from public.discount_brands db
        join public.brands b on b.id=db.brand_id
        where db.discount_id=v_discount.id
          and b.name=coalesce(v_item->>'brand','')
      ) then
        v_eligible := v_eligible + coalesce((v_item->>'line_total')::bigint,0);
      end if;
    end loop;

    if v_eligible <= 0 then
      raise exception 'هیچ محصولی از سبد مشمول این کد تخفیف نیست.';
    end if;

    if v_discount.discount_type='percentage' then
      v_discount_amount := floor(v_eligible * v_discount.value / 100.0)::bigint;
    else
      v_discount_amount := v_discount.value;
    end if;

    if v_discount.max_discount is not null then
      v_discount_amount := least(v_discount_amount,v_discount.max_discount);
    end if;

    v_discount_amount := greatest(0,least(v_discount_amount,v_eligible));
  end if;

  v_total := greatest(0,v_subtotal+v_shipping-v_discount_amount);

  v_result := jsonb_build_object(
    'valid', true,
    'mode', v_mode,
    'subtotal', v_subtotal,
    'eligible_subtotal', v_eligible,
    'discount', v_discount_amount,
    'shipping_cost', v_shipping,
    'total', v_total,
    'discount_id', v_discount_id,
    'discount_code', v_discount_code,
    'message', case when v_discount_id is null then 'سبد آماده است.' else 'کد تخفیف معتبر است.' end
  );

  if v_mode='preview' then
    return v_result;
  end if;

  v_ip_text := split_part(coalesce(current_setting('request.headers', true)::json->>'x-forwarded-for',''), ',', 1);
  begin
    v_ip := nullif(trim(v_ip_text),'')::inet;
  exception when others then
    v_ip := null;
  end;

  if v_ip is not null and (
    select count(*) from private.azim_cart_rate_limits
    where ip=v_ip and created_at > now()-interval '10 minutes'
  ) >= 8 then
    raise exception 'تعداد درخواست‌های ثبت سفارش زیاد است؛ چند دقیقه بعد دوباره تلاش کنید.';
  end if;

  if v_mobile <> '' and (
    select count(*) from private.azim_cart_rate_limits
    where mobile=v_mobile and created_at > now()-interval '10 minutes'
  ) >= 5 then
    raise exception 'برای این شماره، تعداد درخواست‌های ثبت سفارش در این بازه زیاد است.';
  end if;

  insert into public.customers(full_name,mobile,email,address,city,notes)
  values(
    left(trim(p_full_name),120),
    v_mobile,
    nullif(trim(coalesce(p_email,'')),''),
    nullif(trim(coalesce(p_address,'')),''),
    nullif(trim(coalesce(p_city,'')),''),
    'ثبت‌شده از سبد خرید سایت'
  )
  on conflict (mobile) do update set
    full_name=coalesce(nullif(left(trim(excluded.full_name),120),''),public.customers.full_name),
    email=coalesce(nullif(trim(excluded.email),''),public.customers.email),
    address=coalesce(nullif(trim(excluded.address),''),public.customers.address),
    city=coalesce(nullif(trim(excluded.city),''),public.customers.city),
    updated_at=now()
  returning id into v_customer_id;

  v_order_code := 'AZ-' || to_char(now(),'YYYYMMDD-HH24MISS') || '-' || upper(substr(md5(random()::text),1,5));

  insert into public.orders(
    order_code,customer_id,status,payment_status,shipping_status,
    subtotal,discount,discount_id,discount_code,shipping_cost,total,notes
  )
  values(
    v_order_code,v_customer_id,'pending','unpaid','pending',
    v_subtotal,v_discount_amount,v_discount_id,v_discount_code,v_shipping,v_total,
    'ثبت از سبد خرید آنلاین؛ پرداخت و تأیید نهایی توسط فروشگاه انجام می‌شود.'
  )
  returning id into v_order_id;

  insert into public.order_items(
    order_id,product_id,product_name,sku,quantity,unit_price,variant,line_total
  )
  select
    v_order_id,
    (x->>'product_id')::uuid,
    x->>'product_name',
    nullif(x->>'sku',''),
    (x->>'quantity')::integer,
    (x->>'unit_price')::bigint,
    case when nullif(x->>'variant_label','') is null then null else jsonb_build_object('label',x->>'variant_label') end,
    (x->>'line_total')::bigint
  from jsonb_array_elements(v_lines) x;

  delete from public.discount_redemptions where order_id=v_order_id;

  if v_discount_id is not null then
    insert into public.discount_redemptions(
      discount_id,customer_id,order_id,code_used,discount_amount,redeemed_at,created_by
    )
    values(v_discount_id,v_customer_id,v_order_id,v_discount_code,v_discount_amount,now(),null);
  end if;

  insert into private.azim_cart_rate_limits(ip,mobile)
  values(v_ip, nullif(v_mobile,''));

  return v_result || jsonb_build_object(
    'order_id',v_order_id,
    'order_code',v_order_code,
    'customer_id',v_customer_id,
    'message','درخواست سفارش ثبت شد؛ برای هماهنگی نهایی فروشگاه با شما تماس می‌گیرد.'
  );
end;
$function$


revoke all on function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) to anon, authenticated;
