-- Azim Abzar security hardening (production)
-- Applied to Supabase project lzkrwtnylkordkwkdyzp on 2026-09-19.
--
-- Goals:
-- 1) Keep guest checkout available without exposing business tables.
-- 2) Move SECURITY DEFINER order logic out of the exposed public schema.
-- 3) Require MFA (JWT aal2) for all authenticated admin/sales authorization.
-- 4) Rate-limit public order/contact submissions.
-- 5) Minimize anonymous table/function privileges and future default grants.

-- Private schema is not part of the public Data API exposure surface.
grant usage on schema private to anon;

-- Public checkout endpoint is only an INVOKER wrapper.
alter function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb)
  set schema public;

create or replace function public.azim_cart_checkout(
  p_mode text default 'preview',
  p_full_name text default null,
  p_mobile text default null,
  p_email text default null,
  p_address text default null,
  p_city text default null,
  p_discount_code text default null,
  p_items jsonb default '[]'::jsonb
)
returns jsonb
language sql
security invoker
set search_path to ''
as $$
  select private.azim_cart_checkout(
    p_mode,p_full_name,p_mobile,p_email,p_address,p_city,p_discount_code,p_items
  );
$$;

revoke all on function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) to anon;
revoke execute on function public.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) from authenticated;

-- Internal implementation is not exposed through public REST schema.
revoke all on function private.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) from public;
grant execute on function private.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) to anon;
revoke execute on function private.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) from authenticated;
alter function private.azim_cart_checkout(text,text,text,text,text,text,text,jsonb) set statement_timeout='5s';

-- Anonymous clients only need catalog/content reads plus inquiry creation.
revoke all on table public.products, public.categories, public.brands, public.site_content, public.inquiries from anon;
grant select on public.products, public.categories, public.brands, public.site_content to anon;
grant insert on public.inquiries to anon;

revoke all on table public.admin_users, public.audit_logs, public.customers,
  public.discount_brands, public.discount_categories, public.discount_customers,
  public.discount_products, public.discount_redemptions, public.discounts,
  public.media_assets, public.order_items, public.orders from anon;

revoke references, trigger, truncate on all tables in schema public from anon;
revoke references, trigger, truncate on all tables in schema public from authenticated;

-- Public inquiry inserts may only create a clean, new contact request.
drop policy if exists "Public can create inquiries" on public.inquiries;
create policy "Public can create clean inquiries"
on public.inquiries
for insert to anon
with check (
  coalesce(status,'new')='new'
  and coalesce(priority,'normal')='normal'
  and coalesce(source,'contact_form')='contact_form'
  and admin_notes is null
  and handled_by is null
);

create table if not exists private.azim_inquiry_rate_limits (
  id bigint generated by default as identity primary key,
  ip inet,
  mobile text,
  created_at timestamptz not null default now()
);
create index if not exists azim_inquiry_rate_limits_ip_idx
  on private.azim_inquiry_rate_limits(ip, created_at desc);
create index if not exists azim_inquiry_rate_limits_mobile_idx
  on private.azim_inquiry_rate_limits(mobile, created_at desc);

create or replace function private.azim_check_inquiry_rate()
returns trigger
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_ip inet := null;
  v_ip_text text := split_part(
    coalesce(current_setting('request.headers', true)::json->>'x-forwarded-for',''),
    ',', 1
  );
  v_mobile text := regexp_replace(trim(coalesce(new.mobile,'')), '\\s+', '', 'g');
begin
  begin
    v_ip := nullif(trim(v_ip_text),'')::inet;
  exception when others then
    v_ip := null;
  end;

  if v_ip is not null and (
    select count(*) from private.azim_inquiry_rate_limits
    where ip=v_ip and created_at > now()-interval '10 minutes'
  ) >= 10 then
    raise exception 'تعداد درخواست‌های ارتباطی زیاد است؛ چند دقیقه بعد دوباره تلاش کنید.';
  end if;

  if v_mobile <> '' and (
    select count(*) from private.azim_inquiry_rate_limits
    where mobile=v_mobile and created_at > now()-interval '10 minutes'
  ) >= 5 then
    raise exception 'برای این شماره، تعداد درخواست‌های ارتباطی در این بازه زیاد است.';
  end if;

  insert into private.azim_inquiry_rate_limits(ip,mobile)
  values(v_ip, nullif(v_mobile,''));
  return new;
end;
$$;

revoke all on function private.azim_check_inquiry_rate() from public, anon, authenticated;
drop trigger if exists trg_azim_inquiry_rate on public.inquiries;
create trigger trg_azim_inquiry_rate
before insert on public.inquiries
for each row execute function private.azim_check_inquiry_rate();

-- MFA is a database-level authorization requirement, not only a UI check.
create or replace function private.has_azim_role(allowed_roles text[])
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select coalesce(auth.jwt()->>'aal','aal1')='aal2'
    and exists (
      select 1 from public.admin_users
      where user_id=auth.uid()
        and is_active=true
        and role=any(allowed_roles)
    );
$$;

create or replace function private.is_azim_admin()
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select coalesce(auth.jwt()->>'aal','aal1')='aal2'
    and exists (
      select 1 from public.admin_users
      where user_id=auth.uid()
        and is_active=true
    );
$$;

-- Future public tables/functions created by postgres start with no anon/authenticated grant.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated;
